version: "3.9"

services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-server
    env_file: .code.env
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Seoul
    volumes:
    - ./data/code-server:/config
    - ./site:/config/workspace
    - ..:/config/home
    ports:
     - 80:8443
    restart: unless-stopped 
