version: "3.9"

services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    env_file: .code.env
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Seoul
    volumes:
    - ./data/code-server:/config
    - ./site:/config/site
    ports:
     - 14491:8443
    restart: unless-stopped 